### PR TITLE
Added howto contribute description to Teams and Publication

### PR DESCRIPTION
**Pull request by engelmannc**
For consistency and to link the GitHub repository, I added a howto contribute description to the Teams and Publication section.

### CODE REVIEW

**Comment by naughtont3** [comment]
To help ensure we know when ready for someone to get a review, I've added a new label `ready-for-review`.  I'd suggest adding that label (and assigning a person) so people know for sure something is ready to be reviewed.  

I also added a `ready-to-merge` label that people can tag PRs with to ensure things are good (to avoid any doubt from CI/checkers).

**Comment by naughtont3** [comment]
Also, see these suggestions/guidelines for adding the "contributing" info for the repo.
 - [Writing contributing guidelines](https://docs.github.com/articles/setting-guidelines-for-repository-contributors/)

**Review by naughtont3 — COMMENTED** [review]
These changes are fine.  However, I wonder if we should call this part of the document `About` instead of `Team & Publications`.  It is more a page to get more info **about** the artifacts/project/pubs/team (sort of a catch all).

**Comment by engelmannc** [comment]
[like]  Engelmann, Christian reacted to your message:
________________________________
From: Thomas Naughton ***@***.***>
Sent: Thursday, September 26, 2024 8:21:30 PM
To: ORNL/intersect-architecture ***@***.***>
Cc: Engelmann, Christian ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [ORNL/intersect-architecture] Added howto contribute description to Teams and Publication (PR #13)


@naughtont3 commented on this pull request.

These changes are fine. However, I wonder if we should call this part of the document About instead of Team & Publications. It is more a page to get more info about the artifacts/project/pubs/team (sort of a catch all).

**Comment by engelmannc** [comment]
Interesting that liking the e-mail in Outlook does get added as a comment. Nice integration.

"About" may be the right name for this section, but it also sounds a bit generic. IDK

**Comment by naughtont3** [comment]
> "About" may be the right name for this section, but it also sounds a bit generic. IDK

Agree, but this page is sort of a catch all for info and thinking i'd just have to click to know what an "About" page contains. Whereas would not expect to get contrib info on the Team/Pubs page.

**Comment by engelmannc** [comment]
[like]  Engelmann, Christian reacted to your message:
________________________________
From: Thomas Naughton ***@***.***>
Sent: Thursday, September 26, 2024 8:39:34 PM
To: ORNL/intersect-architecture ***@***.***>
Cc: Engelmann, Christian ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [ORNL/intersect-architecture] Added howto contribute description to Teams and Publication (PR #13)


"About" may be the right name for this section, but it also sounds a bit generic. IDK

Agree, but this page is sort of a catch all for info and thinking i'd just have to click to know what an "About" page contains. Whereas would not expect to get contrib info on the Team/Pubs page.

**Review by naughtont3 — APPROVED** [review]

**Pull request merged**
