### PR TITLE
Cleaned up Message Schema section

### PR DESCRIPTION
**Pull request by engelmannc**
- Renamed the section and contained subsection
- Presented the message types clearer
- Made the references conform
- Moved all the files of this section into one folder
- Renamed the section file and folder

### CODE REVIEW

**Comment by engelmannc** [comment]
Please take a quick look at this and approve this request if appropriate. You can see how the new Message Schema section looks like here: https://intersect-architecture--27.org.readthedocs.build/en/27/sos/data/messages.html

**Review by pwidene — APPROVED** [review]
LGTM

**Comment by pwidene** [comment]
Not sure about the desired workflow from here, am I to do the merge after I review?

**Comment by engelmannc** [comment]
We still need to write that up, but it is generally preferred to leave the merge up to the author.

**Pull request merged**
