### PR TITLE
aam: sos opview and image(s)

### PR DESCRIPTION
**Pull request by naughtont3**

### CODE REVIEW

**Comment by engelmannc** [comment]
Looks already pretty good. A few edits:

- ADAMANTINE is an acronym and therefore capitalized.
- "analysis cluster"=> "analysis cluster computer" (this needs to be readable by a non-geek)
- "The device can only use one mode at a time." => "The device can only use one mode at a time, additive or subtractive. " (for clarity)

**Comment by naughtont3** [comment]
>     * "analysis cluster"=> "analysis cluster computer" (this needs to be readable by a non-geek)

Ok, will make this lower case to match other spots in the file.  But the name of the cluster is "Analysis", like "Frontier".  It is not really useful to have that name, and agree more important to be readable.

**Comment by engelmannc** [comment]
[like]  Engelmann, Christian reacted to your message:
________________________________
From: Thomas Naughton ***@***.***>
Sent: Friday, September 27, 2024 3:43:07 PM
To: ORNL/intersect-architecture ***@***.***>
Cc: Engelmann, Christian ***@***.***>; Review requested ***@***.***>
Subject: [EXTERNAL] Re: [ORNL/intersect-architecture] aam: sos opview and image(s) (PR #15)


* "analysis cluster"=> "analysis cluster computer" (this needs to be readable by a non-geek)


Ok, will make this lower case to match other spots in the file. But the name of the cluster is "Analysis", like "Frontier". It is not really useful to have that name, and agree more important to be readable.

**Review by engelmannc — APPROVED** [review]

**Comment by engelmannc** [comment]
Can this be merged?

**Comment by naughtont3** [comment]
i squashed the commits.  This should now be ready to merge.

**Pull request merged**
