### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by naughtont3**
CC-BY 4.0 text

### CODE REVIEW

**Comment by naughtont3** [comment]
Closes #11

**Comment by naughtont3** [comment]
INTERSECT Architecture © 2021 by INTERSECT Architecture Team, Oak Ridge National Laboratory, managed by UT-Battelle LLC is licensed under CC BY 4.0. To view a copy of this license, visit https://creativecommons.org/licenses/by/4.0/

**Comment by naughtont3** [comment]
Sent email to get confirmation that this is appropriate info.

Which was based on the webform using the following details:

```
Attribution Details
Filling out this form is optional, but helps others attribute your work to you, and fills in machine-readable code.
 
Title of Work: INTERSECT Architecture
Creator of Work*: INTERSECT Architecture Team, Oak Ridge National Laboratory, managed by UT-Battelle LLC
Link to Work: https://intersect-architecture.readthedocs.io/
Link to Creator Profile: https://github.com/ORNL/intersect-architecture 
Year Of Creation: 2021 
 
*In addition to the creator of the work, include here any others who should receive attribution. For example, if you created a work on behalf of your employer who owns copyright in the work, you may want to include your employer’s name as one of the attribution parties.
```

**Comment by naughtont3** [comment]
TODO: Add the brief CC-BY blurb to visible area of the rendered webpage(s) w/ href to actual license at CC.org

**Comment by naughtont3** [comment]
Decide if footer should have long or short form of Licensed by text.  We should squash all this too.

**Comment by naughtont3** [comment]
Waiting on proper verbiage for contributors (e.g., should we use INTERSECT Team/ORNL/UT-B) or just one of those or whatever.  Pending discussion in emails (26sep2024).

**Comment by naughtont3** [comment]
Added all the items we talked about.  I have a hard-coded URL in html footer to the team anchor.  This lives in the `_templates/footer.html`, and the few tricks I tried with `html_context` changes in the `conf.py` seemed to not be any better.  For now, this seems good enough and we can open another PR to fix this hardcode in footer.

**Comment by engelmannc** [comment]
So, the footer now has team twice. Can we just make the "INTERSECT Architecture Team" in the copyright a link? Maybe by:

copyright = f'2021-{current_year}' in conf.py

and then using copyright and author separately in the footer?

**Comment by naughtont3** [comment]
Yes, I agree. I will take another swing.

**Comment by engelmannc** [comment]
"INTERSECT Team" => "INTERSECT Architecture Team"

Also, about order and spacing in the footer. Maybe:

```
Interconnected Science Ecosystem | Oak Ridge National Laboratory

© Copyright 2021-2024, INTERSECT Architecture Team. Last updated on Oct 01, 2024.

Licensed under CC BY 4.0 International
```

**Comment by naughtont3** [comment]
> "INTERSECT Team" => "INTERSECT Architecture Team"

Note, switched to using the `author` field from conf.py for setting this string instead of hardcode in footer itself.

**Review by engelmannc — APPROVED** [review]

**Pull request merged**
